// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elanffudgtererfcpudy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYW5mZnVkZ3RlcmVyZmNwdWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzE3NzMsImV4cCI6MjA1NTY0Nzc3M30.1zae11KI2__j-BqmhisKV0AvMeXtU-zpeDOuNYyk-Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);